spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive-client
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
      data-locations: classpath:db/init.sql
  jpa:
    defer-datasource-initialization: true
logging:
  level:
    org.springframework.r2dbc: DEBUG